project:
  type: website

website:
  title: "Shubham's blog"
  description: personal musings of shubham soni
  repo-url: https://github.com/
  site-url: https://shubxam.codes
  repo-subdir: shubxam/shubxam.github.io
  repo-actions: source
  google-analytics:
    tracking-id: G-51BMHSVQD5
    storage: none
  navbar:
    left:
      - posts.qmd
      - projects.qmd
    right: 
      - icon: rss
        href: posts.xml

format:
  html:
    theme:
      dark: cyborg
      light: lux
    css: styles.css
    toc: true
    monofont: JetBrains Mono



